### ISSUE TITLE
regression: can't run Spark tools  on local files when using yarn

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1417]
I'm almost certain this used to work.

```
./bin/gatk/gatk-launch FlagStatSpark -I file:///local/dev/akiezun/bin/gatk/src/test/resources/org/broadinstitute/hellbender/tools/valid.bam -- --sparkRunner SPARK --sparkMaster yarn-client
```

It's fine when running a LOCAL runner, or when the file is on HDFS. 

When resolving the ticket, make sure to devise a way (or at least enter a ticket) to prevent this from happening again - ie some way to discover this kind of problem.

**Comment by lbergelson** [comment]
@akiezun Are you running this on your laptop or on one of the dataflow nodes?  I suspect it will work on your laptop but not on the dataflow nodes.

I believe this is the inverse problem of #1324

**Comment by akiezun** [comment]
this is on yarn on dataflow01

**Comment by lbergelson** [comment]
This same issue is coming up in a number of different ways.  What's happening is that we ask for the `FileSystem` and then try to open a path using whatever it gives back.  The `FileSystem` it returns only knows how to open 1 type of file, either file:/// or hdfs:///.  We could specify a specific file system, but I'm afraid that there will be nasty consequences from that that I don't understand... like getting the wrong hdfs block size or something like that.

```
          FileSystem fs = FileSystem.get(ctx.hadoopConfiguration());
            Path path = fs.makeQualified(new Path(filePath));
            if (fs.isDirectory(path)) {
                FileStatus[] bamFiles = fs.listStatus(path, new PathFilter() {
                    private static final long serialVersionUID = 1L;
                    @Override
                    public boolean accept(Path path) {
                        return path.getName().startsWith(HADOOP_PART_PREFIX);
                    }
                });
                if (bamFiles.length == 0) {
                    throw new UserException("No BAM files to load header from in: " + path);
                }
                path = bamFiles[0].getPath(); // Hadoop-BAM writes the same header to each shard, so use the first one
            }
            return SAMHeaderReader.readSAMHeaderFrom(path, ctx.hadoopConfiguration());
```

**Comment by lbergelson** [comment]
If you `git bisect` can you find a commit where this does work?

**Comment by lbergelson** [comment]
I was assuming that this would be fixed by #1433, but it only fixed the inverse of this problem.  It's possible now to load HDFS files from the local runner using the full namenode path 

i.e.  
`hdfs://dataflow01.broadinstitute.org/user/louisb/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam`, 

Loading files with the sparkRunner and yarn-client is still failing.    

We're getting a new error now though.

```
java.lang.IllegalArgumentException: unknown SAM format, cannot create RecordReader: file:/local/dev/akiezun/bin/gatk/src/test/resources/org/broadinstitute/hellbender/tools/valid.bam
	at org.seqdoop.hadoop_bam.AnySAMInputFormat.createRecordReader(AnySAMInputFormat.java:181)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:151)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:124)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:65)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lbergelson** [comment]
We've been hit with a collective case of confusion.  Of course this is going to fail.  We're accessing a file on **local**.  This is not visible to the executors on the other nodes.  Thus the explosion.

**Comment by droazen** [comment]
Doh! Perhaps we could improve the error message in this case?

**Comment by lbergelson** [comment]
Yes. We desperately need to improve error messages for hadoop bam.

**Comment by droazen** [comment]
Updated the title of this ticket to clarify that the task is now just to improve the error message, not fix an actual bug.

**Comment by akiezun** [comment]
this is the same as #1452. The bug is in hadoop-bam - let's not put a bandaid for that here.

**Comment by akiezun** [comment]
opened https://github.com/HadoopGenomics/Hadoop-BAM/issues/79

blocked until that is fixed. not alpha-1

**Comment by tomwhite** [comment]
@akiezun I created a fix for https://github.com/HadoopGenomics/Hadoop-BAM/issues/79 in https://github.com/HadoopGenomics/Hadoop-BAM/pull/99, which should fix this. Can you take a look?

**Comment by akiezun** [comment]
yes, though not today

**Comment by akiezun** [comment]
@tomwhite  So I'm running on the latest gatk which uses hadoop-bam 7.6.0 (which i think includes those fixes) and I still get this error. I'm running on a dataproc cluster and my exact commandline is:
```
./gatk-launch FlagStatSpark -I file:///home/akiezun/gatk/src/test/resources/org/broadinstitute/hellbender/tools/valid.bam -- --sparkRunner SPARK --sparkMaster yarn-client
```

the file `/home/akiezun/gatk/src/test/resources/org/broadinstitute/hellbender/tools/valid.bam` does exit locally on the master node.

Can you reproduce it too? What do you get?

**Comment by akiezun** [comment]
assigning to @droazen for dispatch
