### ISSUE TITLE
Ensure that multi-threaded AVX PairHMM falls back to single-threaded mode when OpenMP is not available or is the wrong version

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1819]
What is the current behavior when OpenMP is not available or is the wrong version on a Linux system? If the answer is "it blows up with a gross error", then let's patch the code so that it gracefully falls back to the single-threaded version, as on a Mac.

**Comment by droazen** [comment]
For @gspowley

**Comment by gspowley** [comment]
Right, there's not a graceful fallback if OpenMP is not supported at this point. I'll start looking into it.

**Comment by akiezun** [comment]
@droazen do you want this for compile time or run time? Both can fail.

**Comment by droazen** [comment]
@akiezun I'm mainly concerned with having a graceful fallback at runtime, though it would also be good if the GATK could be made to compile on Linux when OpenMP is not present / is the wrong version. The latter is a temporary issue, however, pending the move to a separate repository for the native code.

**Comment by droazen** [comment]
The OpenMP stuff is causing problems for us already when the correct versions of the libraries are not present. We are going to back it out in master until this ticket (adding a fallback when OpenMP can't be loaded on Linux) is done.

**Comment by akiezun** [comment]
either fallback to 1 core or a (maybe preferably) statically linked version of OMP libraries so that people can run it on machines that do not have the same exact layout of dynamic OMP libraries as the machine on which the so file was made.

**Comment by gspowley** [comment]
I'd prefer to fix this in the native library. Is that ok? We're focusing on bringing up the native library now.

**Comment by akiezun** [comment]
yes that's fine

**Comment by droazen** [comment]
@gspowley is this fixed now?

**Comment by gspowley** [comment]
It's not fixed yet. The current release of GKL (0.1.1) only has single-threaded AVX PairHMM.

**Comment by droazen** [comment]
Ok, moving to alpha-3 then

**Comment by gspowley** [comment]
The first step of resolving this issue is merged into GKL. The approach is described in https://github.com/Intel-HLS/GKL/pull/25.

**Next steps**
- [ ] Resolve #1946 
- [ ] Resolve https://github.com/Intel-HLS/GKL/issues/26
