### ISSUE TITLE
FilterMutectCalls trips on non-int value in MFRL tag

### ISSUE THREAD

**Issue by dariober** [broadinstitute/gatk#4363]
Hi- I'm using `FilterMutectCalls` on a vcf produced by mutect2 (same gatk version). I get the following exception from `FilterMutectCalls`:

```
INFO annotation 'MFRL' contains a non-int value '7.97254e+06'
```

This is odd since the MFRL is a FORMAT tag, not INFO and anyway is of type float:

```
zcat gatk/TT001T03.snv.vcf.gz | grep '##' | grep MFRL
##FORMAT=<ID=MFRL,Number=R,Type=Float,Description="median fragment length">
```

The faulty record:

```
zcat gatk/TT001T03.snv.vcf.gz | grep '7.97254e+06'
chr6	32197424	.	G	A	.	.	DP=626;ECNT=1;NLOD=88.13;N_ART_LOD=1.78;POP_AF=0.001;P_GERMLINE=-86.27;TLOD=4.57;	GT:AD:AF:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB	0/0:323,3:0.035:172,3:151,0:41:141,254:60:27:.:.	0/1:264,3:0.038:127,1:137,2:41:124,7.97254e+06:60:27:0.01,0,0.011:0.001247,0.011,0.987
```

**EDIT**: It appears that the int 7972545 is converted to 7.97254e+06 after I passed the vcf file through a custom filter, so not really a fault of gatk (apologies). Still '7.97254e+06' should be a valid float.

Full stack trace:

```
gatk FilterMutectCalls --variant gatk/TT001T03.snv.vcf.gz --output test.vcf.gz

Using GATK jar /home/db291g/applications/gatk/gatk-4.0.1.0/gatk-package-4.0.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /home/db291g/applications/gatk/gatk-4.0.1.0/gatk-package-4.0.1.0-local.jar FilterMutectCalls --variant gatk/TT001T03.snv.vcf.gz --output test.vcf.gz
10:10:10.424 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/db291g/applications/gatk/gatk-4.0.1.0/gatk-package-4.0.1.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
10:10:10.528 INFO  FilterMutectCalls - ------------------------------------------------------------
10:10:10.528 INFO  FilterMutectCalls - The Genome Analysis Toolkit (GATK) v4.0.1.0
10:10:10.528 INFO  FilterMutectCalls - For support and documentation go to https://software.broadinstitute.org/gatk/
10:10:10.529 INFO  FilterMutectCalls - Executing as db291g@login01 on Linux v2.6.32-431.23.3.el6.x86_64 amd64
10:10:10.529 INFO  FilterMutectCalls - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
10:10:10.529 INFO  FilterMutectCalls - Start Date/Time: February 7, 2018 10:10:10 AM GMT
10:10:10.529 INFO  FilterMutectCalls - ------------------------------------------------------------
10:10:10.529 INFO  FilterMutectCalls - ------------------------------------------------------------
10:10:10.529 INFO  FilterMutectCalls - HTSJDK Version: 2.14.1
10:10:10.529 INFO  FilterMutectCalls - Picard Version: 2.17.2
10:10:10.529 INFO  FilterMutectCalls - HTSJDK Defaults.COMPRESSION_LEVEL : 1
10:10:10.530 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:10:10.530 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:10:10.530 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:10:10.530 INFO  FilterMutectCalls - Deflater: IntelDeflater
10:10:10.530 INFO  FilterMutectCalls - Inflater: IntelInflater
10:10:10.530 INFO  FilterMutectCalls - GCS max retries/reopens: 20
10:10:10.530 INFO  FilterMutectCalls - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
10:10:10.530 INFO  FilterMutectCalls - Initializing engine
10:10:10.877 INFO  FeatureManager - Using codec VCFCodec to read file file:///scratch/dberaldi/projects/20180204_combine_callers/gatk/TT001T03.snv.vcf.gz
10:10:10.981 INFO  FilterMutectCalls - Done initializing engine
10:10:11.035 INFO  ProgressMeter - Starting traversal
10:10:11.036 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
10:10:11.331 INFO  FilterMutectCalls - Shutting down engine
[February 7, 2018 10:10:11 AM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.FilterMutectCalls done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=933756928
org.broadinstitute.hellbender.exceptions.GATKException: INFO annotation 'MFRL' contains a non-int value '7.97254e+06'
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.lambda$attributeValueToIntArray$1(GATKProtectedVariantContextUtils.java:134)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.IntPipeline.toArray(IntPipeline.java:502)
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.attributeValueToIntArray(GATKProtectedVariantContextUtils.java:154)
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.getAttributeAsIntArray(GATKProtectedVariantContextUtils.java:81)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.getIntArrayTumorField(Mutect2FilteringEngine.java:235)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.applyMedianFragmentLengthDifferenceFilter(Mutect2FilteringEngine.java:106)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.calculateFilters(Mutect2FilteringEngine.java:228)
	at org.broadinstitute.hellbender.tools.walkers.mutect.FilterMutectCalls.apply(FilterMutectCalls.java:121)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
	at org.broadinstitute.hellbender.Main.main(Main.java:275)
Caused by: java.lang.NumberFormatException: For input string: "7.97254e+06"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.lambda$attributeValueToIntArray$1(GATKProtectedVariantContextUtils.java:132)
	... 32 more
```

**Comment by dariober** [comment]
For the record, the conversion from '7972545' to '7.97254e+06' happens when the vcf file is passed through `bcftools`.

**Comment by davidbenjamin** [comment]
Fixed in PR #4466.

**Comment by dariober** [comment]
Sorry to be a pain... I'm still getting this problem with 4.0.2.1, which according to the tag [description](https://github.com/broadinstitute/gatk/releases/tag/4.0.2.1) should have this issue fixed.

```
Using GATK jar /home/db291g/applications/gatk/gatk-4.0.2.1/gatk-package-4.0.2.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /home/db291g/applications/gatk/gatk-4.0.2.1/gatk-package-4.0.2.1-local.jar FilterMutectCalls --variant gatk4/WW00274.vep.vcf.gz --output test.vcf.gz
10:00:20.977 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/db291g/applications/gatk/gatk-4.0.2.1/gatk-package-4.0.2.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
10:00:21.082 INFO  FilterMutectCalls - ------------------------------------------------------------
10:00:21.083 INFO  FilterMutectCalls - The Genome Analysis Toolkit (GATK) v4.0.2.1
10:00:21.083 INFO  FilterMutectCalls - For support and documentation go to https://software.broadinstitute.org/gatk/
10:00:21.083 INFO  FilterMutectCalls - Executing as db291g@login01 on Linux v2.6.32-431.23.3.el6.x86_64 amd64
10:00:21.083 INFO  FilterMutectCalls - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
10:00:21.083 INFO  FilterMutectCalls - Start Date/Time: March 7, 2018 10:00:20 AM GMT
10:00:21.083 INFO  FilterMutectCalls - ------------------------------------------------------------
10:00:21.083 INFO  FilterMutectCalls - ------------------------------------------------------------
10:00:21.084 INFO  FilterMutectCalls - HTSJDK Version: 2.14.3
10:00:21.084 INFO  FilterMutectCalls - Picard Version: 2.17.2
10:00:21.084 INFO  FilterMutectCalls - HTSJDK Defaults.COMPRESSION_LEVEL : 1
10:00:21.084 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:00:21.084 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:00:21.084 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:00:21.084 INFO  FilterMutectCalls - Deflater: IntelDeflater
10:00:21.084 INFO  FilterMutectCalls - Inflater: IntelInflater
10:00:21.084 INFO  FilterMutectCalls - GCS max retries/reopens: 20
10:00:21.084 INFO  FilterMutectCalls - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
10:00:21.084 INFO  FilterMutectCalls - Initializing engine
10:00:21.437 INFO  FeatureManager - Using codec VCFCodec to read file file:///scratch/dberaldi/projects/20170918_sgp_oesophageal/20171002_mutect/gatk4/WW00274.vep.vcf.gz
10:00:21.673 INFO  FilterMutectCalls - Done initializing engine
10:00:21.734 INFO  ProgressMeter - Starting traversal
10:00:21.734 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
10:00:22.290 INFO  FilterMutectCalls - Shutting down engine
[March 7, 2018 10:00:22 AM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.FilterMutectCalls done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=934805504
org.broadinstitute.hellbender.exceptions.GATKException: INFO annotation 'MFRL' contains a non-int value '2.1472e+08'
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.lambda$attributeValueToIntArray$1(GATKProtectedVariantContextUtils.java:134)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.IntPipeline.toArray(IntPipeline.java:502)
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.attributeValueToIntArray(GATKProtectedVariantContextUtils.java:154)
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.getAttributeAsIntArray(GATKProtectedVariantContextUtils.java:81)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.getIntArrayTumorField(Mutect2FilteringEngine.java:235)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.applyMedianFragmentLengthDifferenceFilter(Mutect2FilteringEngine.java:106)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.calculateFilters(Mutect2FilteringEngine.java:228)
	at org.broadinstitute.hellbender.tools.walkers.mutect.FilterMutectCalls.apply(FilterMutectCalls.java:113)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
	at org.broadinstitute.hellbender.Main.main(Main.java:288)
Caused by: java.lang.NumberFormatException: For input string: "2.1472e+08"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.broadinstitute.hellbender.utils.GATKProtectedVariantContextUtils.lambda$attributeValueToIntArray$1(GATKProtectedVariantContextUtils.java:132)
	... 32 more
```

**Comment by davidbenjamin** [comment]
@dariober Does the vcf header coming out of Mutect2 i.e. before any other tools are run say that MFRL is integer type?

**Comment by dariober** [comment]
Hi- The header reports `##FORMAT=<ID=MFRL,Number=R,Type=Float,Description="median fragment length">`

There is an example vcf file, `in.vcf`, [here](https://github.com/dariober/bioinformatics-cafe/tree/master/fixMFRLforMutect/test_data) which I used to hack together a script to fix an input vcf file (see also [test.md](https://github.com/dariober/bioinformatics-cafe/blob/master/fixMFRLforMutect/test.md)).

**Comment by davidbenjamin** [comment]
@dariober The fix is in `Mutect2` itself because that's where the vcf header line for `MFRL` is created.  If you're using an unfiltered vcf from an old release and using the 4.0.2.1 only for `FilterMutectCalls` the problem will remain.

**Comment by dariober** [comment]
@davidbenjamin Ahh, thanks for the clarification, it makes sense now.
